const Realm = require('realm')

function getSettings(realm) {
  const settings = realm.objectForPrimaryKey('BusinessSettings', 'business')
  if (!settings) return null
  return {
    _id: settings._id,
    businessName: settings.businessName,
    logoDataUrl: settings.logoDataUrl,
    phone: settings.phone,
    email: settings.email,
    address: settings.address,
    commercialRegistration: settings.commercialRegistration,
    taxNumber: settings.taxNumber,
    currency: settings.currency,
    taxEnabled: settings.taxEnabled,
    calendarType: settings.calendarType,
    timeFormat: settings.timeFormat,
    theme: settings.theme,
    fontFamily: settings.fontFamily,
    taxRate: settings.taxRate,
    receiptFooter: settings.receiptFooter,
    printAfterPayment: settings.printAfterPayment,
    printDefaultSize: settings.printDefaultSize,
    printColorMode: settings.printColorMode,
    printDirectly: settings.printDirectly === true,
    thermalPaperSize: settings.thermalPaperSize || '80mm',
    customPaperWidth: settings.customPaperWidth || '',
    customPaperHeight: settings.customPaperHeight || '',
    defaultPrinter: settings.defaultPrinter || '',
    barcodePrinter: settings.barcodePrinter || '',
    barcodeLabelSize: settings.barcodeLabelSize || '50x30',
    barcodeShowName: settings.barcodeShowName !== false,
    barcodeShowPrice: settings.barcodeShowPrice !== false,
    barcodeScale: settings.barcodeScale ?? 1.0,
    barcodeFontWeight: settings.barcodeFontWeight || 'bold',
    showCommercialReg: settings.showCommercialReg !== false,
    showTaxReg: settings.showTaxReg !== false,
    showBusinessName: settings.showBusinessName !== false,
    showLogo: settings.showLogo !== false,
    showPhone: settings.showPhone !== false,
    showEmail: settings.showEmail !== false,
    showAddress: settings.showAddress !== false,
    showReceiptFooter: settings.showReceiptFooter !== false,
    showProductsTable: settings.showProductsTable !== false,
    showTotals: settings.showTotals !== false,
    showPaid: settings.showPaid !== false,
    showCashier: settings.showCashier !== false,
    showNotes: settings.showNotes !== false,
    showClientInfo: settings.showClientInfo !== false,
    showSupplierInfo: settings.showSupplierInfo !== false,
    showQR: settings.showQR !== false,
    autoBackup: settings.autoBackup,
    autoBackupInterval: settings.autoBackupInterval,
    autoBackupLastDate: settings.autoBackupLastDate,
    autoBackupPath: settings.autoBackupPath,
    telegramChatId: settings.telegramChatId || '',
    notificationLowStock: settings.notificationLowStock !== false,
    notificationSales: settings.notificationSales !== false,
    notificationPayments: settings.notificationPayments !== false,
    notificationReturns: settings.notificationReturns !== false,
    notificationShifts: settings.notificationShifts !== false,
    notificationExpiry: settings.notificationExpiry !== false,
    seeded: settings.seeded
  }
}

function saveSettings(realm, data) {
  realm.write(() => {
    realm.create('BusinessSettings', {
      _id: 'business',
      businessName: data.businessName || '',
      logoDataUrl: data.logoDataUrl || '',
      phone: data.phone || '',
      email: data.email || '',
      address: data.address || '',
      commercialRegistration: data.commercialRegistration || '',
      taxNumber: data.taxNumber || '',
      currency: data.currency || 'EGP',
      taxEnabled: data.taxEnabled !== false,
      calendarType: data.calendarType || 'gregorian',
      timeFormat: data.timeFormat || '12',
      theme: data.theme || 'light',
      fontFamily: data.fontFamily || 'Cairo',
      taxRate: data.taxRate != null ? Number(data.taxRate) : 14,
      receiptFooter: data.receiptFooter || '',
      printAfterPayment: data.printAfterPayment !== false,
      printDefaultSize: data.printDefaultSize || 'receipt',
      printColorMode: data.printColorMode || 'color',
      printDirectly: data.printDirectly === true,
      thermalPaperSize: data.thermalPaperSize || '80mm',
      customPaperWidth: data.customPaperWidth || '',
      customPaperHeight: data.customPaperHeight || '',
      defaultPrinter: data.defaultPrinter || '',
      barcodePrinter: data.barcodePrinter || '',
      barcodeLabelSize: data.barcodeLabelSize || '50x30',
      barcodeShowName: data.barcodeShowName !== false,
      barcodeShowPrice: data.barcodeShowPrice !== false,
      barcodeScale: data.barcodeScale ?? 1.0,
      barcodeFontWeight: data.barcodeFontWeight || 'bold',
      showCommercialReg: data.showCommercialReg !== false,
      showTaxReg: data.showTaxReg !== false,
      showBusinessName: data.showBusinessName !== false,
      showLogo: data.showLogo !== false,
      showPhone: data.showPhone !== false,
      showEmail: data.showEmail !== false,
      showAddress: data.showAddress !== false,
      showReceiptFooter: data.showReceiptFooter !== false,
      showProductsTable: data.showProductsTable !== false,
      showTotals: data.showTotals !== false,
      showPaid: data.showPaid !== false,
      showCashier: data.showCashier !== false,
      showNotes: data.showNotes !== false,
      showClientInfo: data.showClientInfo !== false,
      showSupplierInfo: data.showSupplierInfo !== false,
      showQR: data.showQR !== false,
    autoBackup: data.autoBackup || false,
    autoBackupInterval: data.autoBackupInterval || 'weekly',
    autoBackupLastDate: data.autoBackupLastDate ? new Date(data.autoBackupLastDate) : null,
    autoBackupPath: data.autoBackupPath || '',
    telegramChatId: data.telegramChatId || '',
    notificationLowStock: data.notificationLowStock !== false,
    notificationSales: data.notificationSales !== false,
    notificationPayments: data.notificationPayments !== false,
    notificationReturns: data.notificationReturns !== false,
    notificationShifts: data.notificationShifts !== false,
    notificationExpiry: data.notificationExpiry !== false,
    seeded: true
    }, Realm.UpdateMode.Modified)
  })
  return getSettings(realm)
}

module.exports = { getSettings, saveSettings }
